const constants = {
	EXTEMPORISE_CHANGE_EVENT: "EXTEMPORISE_CHANGE_EVENT",
	EXTEMPORISE_CREATE: "EXTEMPORISE_CREATE",
	EXTEMPORISE_UPDATE: "EXTEMPORISE_UPDATE",
	EXTEMPORISE_DELETE: "EXTEMPORISE_DELETE"
};
export default constants;